server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/documents
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  numberPrefix: "DOC"
  batchSize: 50
  worker:
    fixedDelayMs: 2000
  workers:
    enabled: false

logging:
  level:
    root: INFO
    ru.itq: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

